# Generated by Django 2.2.7 on 2019-11-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directions',
            options={'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name_plural': 'Meals'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name_plural': 'RecipeIngredients'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name_plural': 'Recipes'},
        ),
    ]
